# Base configs
baseurl: "https://photography.rampatra.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Hard Work for the hard days"
subtitle: "See the world through my eyes!"
author: "Bashir"
header:
 title: "Photography"
 subtitle: "by me or rando on the internet"
footer:
 name: "Hey there, my name is Bashr"
 bio: "I am a founder from Senegal. Love making software and being the guy that get a call when the going get though for others."
 github: ""
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/bayevels"
  github: "https://www.github.com/bayevels"
